name: Swift

on: [push]

jobs:
  test:
    name: Test
    runs-on: macOS-latest
    strategy:
        matrix:
            destination: ['platform=iOS Simulator,OS=13.0,name=iPhone 11 Pro']
    steps:
        - uses: actions/checkout@v1
        
        - name: Install Cocoapods
          run: gem install cocoapods
    
        - name: Start xcodebuild test
          run: xcodebuild clean test -workspace PicsLock.xcworkspace -scheme PicsLock -destination "platform=iOS Simulator,OS=13.2.2,name=iPhone 11 Pro"
