name: Swift

on: [push]

jobs:
  test:
    name: Test
    runs-on: macOS-latest

    steps:
        - uses: actions/checkout@v1
    
        - name: Start xcodebuild test
          run: xcodebuild clean test -project PicsLock.xcodeproj -scheme PicsLock -destination "platform=iOS Simulator,OS=latest,name=iPhone 11 Pro"
